# Generated by Django 3.2 on 2021-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210504_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subtitle',
            field=models.CharField(default='default subtitle', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(),
        ),
    ]
